apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-claim
  annotations:
    volume.aplha.kubernetes.io/storage-class: longhorn
  namespace: 2-tier-appp 
spec:
  storageClassName: "longhorn-static"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-nginx-deployment
  namespace: 2-tier-appp 
spec:
  selector:
    matchLabels:
      app: clear-nginx
  template:
    metadata:
      labels:
        app: clear-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        volumeMounts:
        - mountPath: /var/www/html
          name: site-data
        ports:
        - containerPort: 80
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: demo-pvc-claim
---
apiVersion: v1
kind: Service
metadata:
  name: clear-nginx-service
  namespace: 2-tier-appp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: clear-nginx
  type: ClusterIP
